### ISSUE TITLE
ZRay Laravel Error

### ISSUE THREAD

**Issue by xiregroup** [zend-server-plugins/Laravel#4]
Zend Server 9
Laravel 5.4

FatalErrorException in Logger.php line 616:
Uncaught Exception: Serialization of 'Closure' is not allowed in G:\zend\student\vendor\monolog\monolog\src\Monolog\Logger.php:616
Stack trace:
#0 G:\zend\student\vendor\laravel\framework\src\Illuminate\Log\Writer.php(203): Monolog\Logger->error(Object(Exception), Array)
#1 G:\zend\student\vendor\laravel\framework\src\Illuminate\Log\Writer.php(114): Illuminate\Log\Writer->writeLog('error', Object(Exception), Array)
#2 G:\zend\student\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(71): Illuminate\Log\Writer->error(Object(Exception))
#3 G:\zend\student\app\Exceptions\Handler.php(38): Illuminate\Foundation\Exceptions\Handler->report(Object(Exception))
#4 G:\zend\student\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(80): App\Exceptions\Handler->report(Object(Exception))
#5 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Exception))
#6 {main}
thrown

**Comment by michaeldeepak** [comment]
Fixed https://github.com/zend-server-plugins/Laravel/pull/5
